services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.config:/root/.config:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/.netrc:/root/.netrc:cached
      - /data:/data
    command: sleep infinity
